CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     email VARCHAR(40) NOT NULL UNIQUE,
                                     login VARCHAR(255) NOT NULL UNIQUE,
                                     name VARCHAR(40) NOT NULL,
                                     birthday DATE CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS rating (
                                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genre (
                                     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR (40) UNIQUE
);

CREATE TABLE IF NOT EXISTS friendship_status (
                                                 id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 status VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(40) NOT NULL,
                                     release_date DATE NOT NULL CHECK (films.release_date >= '1895-12-28'),
                                     duration INTEGER NOT NULL CHECK (duration > 0),
                                     description VARCHAR(200),
                                     rating_id INT NOT NULL references rating(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS films_likes (
                                           film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE,
                                           user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                           PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS films_genres (
                                            film_id BIGINT NOT NULL REFERENCES films(id) ON DELETE CASCADE ,
                                            genre_id BIGINT NOT NULL REFERENCES genre(id) ON DELETE CASCADE ,
                                            PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friends (
                                       user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                       friend_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                                       status_id INTEGER NOT NULL REFERENCES friendship_status(id) ON DELETE RESTRICT,
                                       PRIMARY KEY (user_id, friend_id)
);


